### ISSUE TITLE
Make boxmetrics cli as executable and run it globally

### ISSUE THREAD

**Issue by itsabdessalam** [Laurent-PANEK/boxmetrics-cli#4]
As you know I always have to source env in order to run boxmetrics commands. I don't know if it's possible to directly install the tool and run the command without sourcing.

**Comment by l4u23n7p** [comment]
Hi Abdessalam !

I try with commons tools *(`py2exe`, `pyinstaller`, `cx-freeze`)* to create an executable file.
Unfortunately, it's impossible the way the CLI is right now.

**Why ?**

Currently, the project is based on `cement` framework, and the way the framework do is work does not allow to build a binary from it *(with `py2exe`, `pyinstaller` or `cx-freeze`)*.

**Possible Solutions :**

- Find another module who can build a binary from the current project state *(a bit ambitious)*
- Change code of `cement` framework to allow to builders to work *(too tidy)*
- Rewrite the CLI base on another module such as : `cliff`, `click` or even `argparse` *(most realistic solution imo)*

However, this repository, in this current state, is just a temporary tool design to be rewrite later, so this issue will be taken into account for the next major version
